name: Generate packages

on:
  push:
    branches:
      - 'main'
    paths:
      - 'plugins.json'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate packages
        shell: nix develop --command bash -e {0}
        run: |
          nu ./scripts/gen-yazi-plugins.nu
